FROM legisdefagent-base:latest

RUN python -c "from pymilvus.model.hybrid import BGEM3EmbeddingFunction; BGEM3EmbeddingFunction(model_name='BAAI/bge-m3')"

CMD ["python", "-m", "legisdefagent.cli", "run-service"]
